# EXTRA COVARIATES and TASKS CREATION

In [1]:
import pandas as pd
import numpy as np
import datetime
from datetime import timedelta
file_path="~/Documents/Data/Full_MIMIC/"
outfile_path="~/Documents/Data/Full_MIMIC/Clean_data/"

/Users/XXXX/miniconda3/envs/pytorch/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


### EXTRA TASKS

In [2]:
unique_id_dict=pd.read_csv(outfile_path+"UNIQUE_ID_dict.csv")
hadm_ids=unique_id_dict["HADM_ID"]
admissions=pd.read_csv(file_path+"Admissions_processed.csv")
adm=admissions.loc[admissions["HADM_ID"].isin(hadm_ids)].copy() #Select the patients selected earlier.

In [3]:
#We create a new vector for the duration stay.
adm["admit"]=pd.to_datetime(adm["ADMITTIME"])
adm["disc"]=pd.to_datetime(adm["DISCHTIME"])
adm["duration"]=adm["disc"]-adm["admit"]
adm["Value"]=adm["duration"].dt.days

In [4]:
d=unique_id_dict[["HADM_ID","UNIQUE_ID"]].set_index("HADM_ID").to_dict()["UNIQUE_ID"]
adm["UNIQUE_ID"]=adm["HADM_ID"].map(d)

durations_df=adm[["UNIQUE_ID","Value"]].copy()
durations_df.sort_values(by="UNIQUE_ID",inplace=True)
durations_df.to_csv(outfile_path+"complete_durations_vec.csv")

In [5]:
durations_df

UNIQUE_ID  duration_days
12567          0             14
16312          1             12
16974          2              3
75             3              5
11339          4              5
23224          5              9
6257           6              3
5714           7             10
18023          8             13
22326          9              3
977           10              4
4234          11              3
21596         12              3
15734         13             14
17426         14              4
22325         15              5
6791          16              5
9101          17              7
20229         18              3
600           19              4
16744         20              4
4738          21             11
16989         22             18
11217         23              6
810           24              9
20317         25              7
16179         26              7
19957         27              5
12444         28              4
16776         29              7
...          ...            ...
19761      21220              5
815        21221              3
18694      21222              7
2087       21223              5
7237       21224              4
5698       21225              8
2995       21226              7
23058      21227              8
7913       21228             19
5014       21229              6
6532       21230              9
5770       21231             10
7188       21232              6
3398       21233              7
2469       21234              3
3908       21235             14
18263      21236              3
7477       21237              5
8928       21238              9
15787      21239              6
22750      21240             16
15905      21241              6
20926      21242              7
19432      21243             26
19314      21244              7
1641       21245             17
23013      21246              4
8111       21247              6
3025       21248              7
1117       21249              5

[21250 rows x 2 columns]

## Extra Covariates

We want to add the covariates that are used in the SAPSII criterion.

In [23]:
infile_path="~/Documents/Data/Full_MIMIC/Clean_data/"
hadm_ids=pd.read_csv(infile_path+"UNIQUE_ID_dict.csv")["HADM_ID"]
d=pd.read_csv(infile_path+"UNIQUE_ID_dict.csv")[["UNIQUE_ID","HADM_ID"]]

In [30]:
admissions=pd.read_csv(file_path+"Admissions_processed.csv")
adm=admissions.loc[admissions["HADM_ID"].isin(hadm_ids)].copy() #Select the patients selected earlier.
adm=adm.merge(d,on="HADM_ID")

In [34]:
#Age
adm["birth_date"]=pd.to_datetime(adm["DOBTIME"])
adm["admit_date"]=pd.to_datetime(adm["ADMITTIME"])
adm["age"]=(adm["admit_date"]-adm["birth_date"]).dt.days//365

In [35]:
#Admission type
adm["EMERGENCY_ADMISSION"]=1*(adm["ADMISSION_TYPE"]=="EMERGENCY")
adm["ELECTIVE_ADMISSION"]=1*(adm["ADMISSION_TYPE"]=="ELECTIVE")
adm["URGENT_ADMISSION"]=1*(adm["ADMISSION_TYPE"]=="URGENT")

In [43]:
cov=pd.read_csv(infile_path+"complete_covariates.csv")

In [44]:
cov=cov.merge(adm[["age","EMERGENCY_ADMISSION","ELECTIVE_ADMISSION","URGENT_ADMISSION","UNIQUE_ID"]],on="UNIQUE_ID")

In [45]:
cov.to_csv(infile_path+"complete_covariates_extended.csv")

In [10]:
pd.read_csv(infile_path+"label_dict.csv")["LABEL"].unique()

array(['Anion Gap', 'Bicarbonate', 'Calcium, Total', 'Chloride',
       'Creatinine', 'Glucose', 'Magnesium', 'Phosphate', 'Potassium',
       'Sodium', 'Alkaline Phosphatase',
       'Asparate Aminotransferase (AST)', 'Bilirubin, Total',
       'Urea Nitrogen', 'Basophils', 'Eosinophils', 'Hematocrit',
       'Hemoglobin', 'Lymphocytes', 'MCH', 'MCHC', 'MCV', 'Monocytes',
       'Neutrophils', 'Platelet Count', 'RDW', 'Red Blood Cells',
       'White Blood Cells', 'PTT', 'Base Excess', 'Calculated Total CO2',
       'Lactate', 'pCO2', 'pH', 'pO2', 'PT',
       'Alanine Aminotransferase (ALT)', 'Specific Gravity',
       'Sodium Chloride 0.9%  FlushDrug Drug', 'D5WDrug Drug',
       'Magnesium SulfateDrug Drug', 'Potassium ChlorideDrug Drug',
       'Potassium Chloride', 'Calcium Gluconate', 'Magnesium Sulfate',
       'Furosemide (Lasix)', 'Insulin - Regular', 'PO Intake',
       'Insulin - Humalog', 'OR Crystalloid Intake', 'Morphine Sulfate',
       'Insulin - Glargine', 'OR Cell Sa

In [25]:
chartevents=pd.read_csv(file_path+"CHARTEVENTS.csv")

KeyboardInterrupt: 

In [84]:
a=None

In [83]:
if a:
    print("oj")

oj


In [86]:
from sklearn.model_selection import KFold

/Users/XXXX/miniconda3/envs/pytorch/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [132]:
k=KFold(n_splits=3,random_state=22)

In [133]:
for train,val in k.split(np.arange(15)):
    print(train)
    print(val)

[ 5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4]
[ 0  1  2  3  4 10 11 12 13 14]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14]


In [134]:
for train,val in k.split(np.arange(15)):
    print(train)
    print(val)

[ 5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4]
[ 0  1  2  3  4 10 11 12 13 14]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14]


In [135]:
for train,val in k.split(np.arange(15)):
    print(train)
    print(val)

[ 5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4]
[ 0  1  2  3  4 10 11 12 13 14]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14]


In [140]:
a=np.array([3,2,1])

In [137]:
a.shape

(1, 3)

In [138]:
b=[4,5,3,2,1]

In [148]:
c=np.arange(15)

In [153]:
c=np.ones((15,15))
c[train,:]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])